services:
  web:
    environment:
      - DB_PASS=123123
    volumes:
      - ./web/scoring/:/app/scoring
      - ./web/src/mwahahavote/static/scores:/app/src/mwahahavote/static/scores
    ports:
      - '5000:80'
    networks:
      - net
networks:
  net:
    name: clasificahumor_net
    external: true
